const User = require("../models/User");
const { SECRET } = require("../config");
const { Strategy, ExtractJwt } = require("passport-jwt");

const opts = {
    jwtFromRequest: ExtractJwt.fromAuthHeaderAsBearerToken,
    // generated by jwtwebtoken
    secretOrKey: SECRET,
    // manually appended
}
module.exports = (passport) => {
    passport.use(new Strategy(opts, async (payload, done) => {
        await User.findById(payload.user_id).then(user => {
            if (user) {
                return done(null, user)
                // done(no error, return user)
            } 
            // if no user
            return done (null, false)
            }).catch(err => {return done (null, false)})
        })
    )
}